spring:
  jpa:
    database: mysql
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        default_batch_fetch_size: 10
  datasource:
    url: jdbc:mysql://mysql:3306/portfolio
    username: root
    password: ENC(+uwc+l2JJcCHSe84RLxD1HuHByHWViOi)
    driver-class-name: com.mysql.cj.jdbc.Driver